AllCops:
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

Style/For:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/StringLiterals:
  Enabled: false