source "https://rubygems.org" do
  gem "capybara"
  gem "rack-test"
  gem "require_all"
  gem "rspec"
  gem "sequel"
  gem "simplecov"
  gem "sinatra"
  gem "sqlite3"
  gem "thin"
  gem "time_difference"
end
