#!/usr/bin/env bash

if [ "$USER" = "codio" ]
then
  # ensure we're in the directory of this script
  cd "${0%/*}"
 
  # copy scripts
  sudo cp sinatra.rb /usr/local/bin/sinatra

  # copy initial .codio file
  cp .codio_init /home/codio/workspace/.codio
  
  echo "Successfully installed"
else
  echo "This script should only be run on Codio"
fi
