require:
  - rubocop-rspec
  - rubocop-sequel

AllCops:
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

RSpec/BeforeAfterAll:
  Enabled: false
  
RSpec/DescribeClass:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
